site_name: ComposeViews

nav:
- Home: index.md
- Documents:
  - Usage: usage.md
- Components:
  - ComposePager: components/composepager.md
  - Banner: components/banner.md
  - PagerIndicator: components/pagerindicator.md
  - ImageBanner: components/ImageBanner.md
  - RefreshLayout: components/RefreshLayout.md
  - GoodTextField and PasswordTextField: components/GoodTextField.md
  - MenuFloatingActionButton: components/MenuFloatingActionButton.md
  - ChainScrollableComponent: components/ChainScrollableComponent.md
  - More: components/More.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences